### PR TITLE
Add support for Firefox on macOS

### PR DESCRIPTION
**Pull request by prplecake**
Transferring PR from barrettfdavis' repo (https://github.com/barrettfdavis/online_actogram/pull/7).

## Todo

- [ ] Sort out multiple Firefox profiles
- [x] Sort out non-predictable suffixes (https://github.com/barrettfdavis/online_actogram/pull/7#issuecomment-1360075972)

### CODE REVIEW

**Comment by lrq3000** [comment]
Thank you very much @prplecake! Please let me know if you need anything or if I can do anything! And of course I'll merge asap if you can implement your idea!

Also I will start versioning this repository to more easily track changes :-) I can also make it into a modern python package. I'll make a separate pr.

**Comment by lrq3000** [comment]
Hey @prplecake , about detecting the profiles, wouldn’t the following solution work?

https://stackoverflow.com/questions/50148814/how-to-get-the-firefox-profile-path-dynamically-in-python

Are you ok that I try to implement it and finish the PR? :-)

**Comment by prplecake** [comment]
I have time to work on it today, so I'll send in some updates shortly.

**Comment by prplecake** [comment]
My latest changes finish the PR in terms of supporting Firefox on macOS (and Linux).

A future enhancement might be to read history data from ALL Firefox profiles to ensure the history snapshot is as complete as possible. (But then we start getting near the mess that is handling multiple devices!)

**Comment by lrq3000** [comment]
Awesome work @prplecake , thank you so much! :D I’m going to merge it in as-is and later implement support for multiple profiles.

But first I’ll try to make this a modern python package so it will be MUCH easier to install and use!

**Comment by lrq3000** [comment]
Thank you so much @prplecake and @Alliegaytor for adding support for Firefox and the code cleanup ❤️ 😄

**Pull request merged**
